export const LOGIN = 'LOGIN'

export const PENDING = '_PENDING'
export const FULFILLED = '_FULFILLED'
export const REJECTED = '_REJECTED'

export const CHANG_COUNT_DOWN_START = 'CHANG_COUNT_DOWN_START'
export const CHANG_COUNT_DOWN_OVER = 'CHANG_COUNT_DOWN_OVER'
export const START_COUNT_DOWN_ONE = 'START_COUNT_DOWN_ONE'
export const COUNT_DOWN_LOADING = 'COUNT_DOWN_LOADING'
export const COUNT_DOWN_OVER = 'COUNT_DOWN_OVER'
